
inherit:
  - resnet50.yaml 
  - datasets_cifar10.yaml

num_classes: 10
epochs: &epochs 5

model:
  classname: models.imnet_resnet.ResNet50
  args:
    pretrained: True
    pretrain_style: 'mocov2_lped'
    checkpoint_path: 'logs/dplppart_cifar10_lr_0.5_nm_0.1_mt_0_sd_2/checkpoints/ckp_best_cifar10-test'

scheduler:
  classname: torch.optim.lr_scheduler.CosineAnnealingLR
  args:
    T_max: *epochs

