
log_interval: 5000
use_cuda: True
save_freq: 1001
batch_size: 64
num_workers: 4
save_all_checkpoints: False

finetune: False
linear_probe: True
use_net_val_mode: False

optimizer:
  classname: torch.optim.SGD
  args:
    lr: 0.5
    momentum: 0.0
    weight_decay: 0.0

criterion:
  classname: torch.nn.CrossEntropyLoss
  args:
    reduction: mean
